2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Configure stats pid to 20644
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/.config/wandb/settings
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/settings
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_init.py:_log_setup():528] Logging user logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/run-20231023_191947-gmgn283a/logs/debug.log
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_init.py:_log_setup():529] Logging internal logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/run-20231023_191947-gmgn283a/logs/debug-internal.log
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f42f5d93850>
2023-10-23 19:19:47,616 INFO    MainThread:20644 [wandb_init.py:init():568] calling init triggers
2023-10-23 19:19:47,617 INFO    MainThread:20644 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'num_epoches': 650, 'learning_rate': 0.05}
2023-10-23 19:19:47,617 INFO    MainThread:20644 [wandb_init.py:init():618] starting backend
2023-10-23 19:19:47,617 INFO    MainThread:20644 [wandb_init.py:init():622] setting up manager
2023-10-23 19:19:47,617 INFO    MainThread:20644 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-23 19:19:47,618 INFO    MainThread:20644 [wandb_init.py:init():628] backend started and connected
2023-10-23 19:19:47,625 INFO    MainThread:20644 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-23 19:19:47,625 INFO    MainThread:20644 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-23 19:19:47,625 INFO    MainThread:20644 [wandb_init.py:init():720] updated telemetry
2023-10-23 19:19:47,636 INFO    MainThread:20644 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-23 19:19:47,790 WARNING MainThread:20644 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 756, in init
    result = run_init_handle.wait(
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/tejas/anaconda3/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/tejas/anaconda3/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Configure stats pid to 20644
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/.config/wandb/settings
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/settings
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:_log_setup():528] Logging user logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/run-20231023_192113-ij054o72/logs/debug.log
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:_log_setup():529] Logging internal logs to /home/tejas/Documents/SMAI/assignment-3-MrTejas/q1/wandb/run-20231023_192113-ij054o72/logs/debug-internal.log
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:init():568] calling init triggers
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'num_epoches': 1000, 'learning_rate': 0.001}
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:init():618] starting backend
2023-10-23 19:21:13,798 INFO    MainThread:20644 [wandb_init.py:init():622] setting up manager
2023-10-23 19:21:13,800 INFO    MainThread:20644 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-23 19:21:13,800 INFO    MainThread:20644 [wandb_init.py:init():628] backend started and connected
2023-10-23 19:21:13,809 INFO    MainThread:20644 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-23 19:21:13,809 INFO    MainThread:20644 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-23 19:21:13,809 INFO    MainThread:20644 [wandb_init.py:init():720] updated telemetry
2023-10-23 19:21:13,819 INFO    MainThread:20644 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-23 19:22:43,939 ERROR   MainThread:20644 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-23 19:22:44,092 ERROR   MainThread:20644 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/tejas/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
